empresa/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('/empleado', 'EmpleadoController');

Route::get('/', function(){
	return redirect(route('empleado.index'));
});

empresa/app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    //escribimos algo para subior
}

empresa/app/Empleado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado extends Model
{
    //
}

empresa/app/Empleado_rol.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Empleado_rol extends Model
{
    protected $table = "Empleado_rol";
}

empresa/app/Rol.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Rol extends Model
{
    protected $table = "Roles";
}

empresa/app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    //
}

empresa/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

empresa/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

empresa/app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Student;
use App\Empleado;
use App\Rol;
use App\Area;
use App\Empleado_rol;

class EmpleadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $areas = Area::all();
        $roles = Rol::all();
        $empleados = Empleado::all();
        return view('empleado', compact('roles', 'areas', 'empleados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $Empleado = new Empleado;
        $Empleado->nombre = $request->nombre;
        $Empleado->email = $request->email;
        $Empleado->sexo = $request->sexo;
        $Empleado->boletin = $request->boletin;
        $Empleado->area_id = $request->area;
        $Empleado->descripcion = $request->descripcion;
        

        if ($Empleado->save()) {

            /* toma la id del registro guardado*/
            $id_empleado = $Empleado->id; 

            $Empleado_rol = new Empleado_rol;
            $Empleado_rol->empleado_id = $id_empleado;
            $Empleado_rol->rol_id = $request->rol;

            if ($Empleado_rol->save()) {
                return redirect(route('empleado.index'));
            }
            


        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

empresa/resources/views/empleado.blade.php
@extends('layouts/layouts')

@section('title', 'Facultades') <!-- titulo de la de la pestaña -->

@section('content')


<div class="container">	
	<br>
	<h1>Crear empleado</h1>
	<form method="post" action="{{route('empleado.store')}}">
		{{csrf_field()}}
		<div class="form-group row" >
			<label for="inputEmail3" class="col-sm-2 col-form-label" style="text-align: right;" >Nombre completo*</label>
			<div class="col-sm-10">
				<input type="text" class="form-control" id="inputEmail3" name="nombre" placeholder="Nombre completo del empleado" required>
			</div>
		</div>
		<div class="form-group row" >
			<label for="inputPassword3" class="col-sm-2 col-form-label" style="text-align: right;" >Correo electronico*</label>
			<div class="col-sm-10">
				<input type="email" class="form-control" id="inputPassword3" name="email" placeholder="Correo electronico" required>
			</div>
		</div>
		<fieldset class="form-group">
			<div class="row">
				<legend class="col-form-label col-sm-2 pt-0" style="text-align: right;">Sexo*</legend>
				<div class="col-sm-10">
					<div class="form-check">
						<input class="form-check-input" type="radio" name="sexo" value="M" id="gridRadios1"  checked>
						<label class="form-check-label" for="gridRadios1">
							Masculino
						</label>
					</div>
					<div class="form-check">
						<input class="form-check-input" type="radio" name="sexo" value="F" id="gridRadios2" >
						<label class="form-check-label" for="gridRadios2">
							Femenino
						</label>
					</div>
				</div>
			</div>
		</fieldset>
		<div class="form-group row">
			<div class="col-sm-2" style="text-align: right;">Area</div>
			<div class="col-sm-10">
				<select class="custom-select" id="" name="area">
					@foreach($areas as $area)
					<option value="{{$area->id}}">{{$area->nombre}}</option>
					@endforeach
				</select>
			</div>
		</div>
		<div class="form-group row">
			<div class="col-sm-2" style="text-align: right;">Descripcion</div>
			<div class="col-sm-10">
				<textarea class="form-control" id="description" name="descripcion" required></textarea> 
			</div>
		</div>
		<div class="form-group row">
			<div class="col-sm-2" style="text-align: right;">boletin</div>
			<div class="col-sm-10">
				<div class="form-check">
					<input class="form-check-input" type="checkbox" id="boletin" name="boletin" value="1">
					<label class="form-check-label" for="gridCheck1">
						boletin
					</label>
				</div>
			</div>
		</div>
		<fieldset class="form-group">
			<div class="row">
				<legend class="col-form-label col-sm-2 pt-0" style="text-align: right;">Roles*</legend>
				<div class="col-sm-10">
					@foreach($roles as $rol)
					<div class="form-check">
						<input class="form-check-input" type="radio" name="rol" value="{{$rol->id}}" id="gridRadios1" v checked>
						<label class="form-check-label" for="gridRadios1">
							{{$rol->nombre}}
						</label>
					</div>
					@endforeach	
					
				</div>
			</div>
		</fieldset>
		
		<div class="form-group row">
			<div class="col-sm-2"></div>
			<div class="col-sm-10">
				<button type="submit" class="btn btn-primary">Crear</button>
			</div>
		</div>

	</form>

	<table class="table">
		<thead class="thead-dark">
			<tr>
				<th scope="col">Nombre</th>
				<th scope="col">Email</th>
				<th scope="col">Sexo</th>
				<th scope="col">Boletín</th>
			</tr>
		</thead>
		<tbody>
			
			@foreach($empleados as $empleado)
			<tr>
				<td>{{$empleado->nombre}}</td>
				<td>{{$empleado->email}}</td>

				@if($empleado->sexo == 'M')	
				<td>Masculino</td>
				@elseif($empleado->sexo == 'F')
				<td>Femenino</td>
				@endif		
				
				@if($empleado->boletin == 1)	
				<td>Sí</td>
				@else
				<td>No</td>
				@endif		 
			</tr>
			@endforeach

			


		</tbody>
	</table>


</div>

empresa/resources/views/layouts/layouts.blade.php
<!DOCTYPE html>
<html>
<style type="text/css">
	body {
  box-sizing: border-box;
}
</style>
<head>
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
	<title>
		@yield('title') 
	</title>
</head>

<body>
	
	@yield('content')
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js"></script>
	<script type="text/javascript">
		$(function(){
			var $create = $("create"); 
			if ($create.length) {
				$create.validate({
					rules:{
						fname:{
							required: true
						}
					},
					messages:{
						fname:{
							required: 'hello'
						}
					}
 				})
			}
		})
	</script>
</body>
</html>